### ISSUE TITLE
Change rule name in assistant template from `hello-world` to something following our own convention

### ISSUE THREAD

**Issue by christianklotz** [sketch-hq/sketch-assistant-template#4]
All rules follow the convention to `{type}-{how}-{what}` (or whatever we called it. Instead of `hello-world` I suggest to apply the same here.

I don't have a solution for a name though 🤔

**Comment by jedrichards** [comment]
I think we got our inspiration from stylelint's naming scheme originally https://stylelint.io/user-guide/rules/about#names

That is two parts, roughly `{thing}-{what-is-checked}`.

Tricky to fit `hello-world` into that pattern, since there's no "thing" (context is global), and nothing is being checked 🙃

**Comment by christianklotz** [comment]
👍 for the clarification. Finally understood 🙂
